# 64-bit Architecture Dependent Config
ARCH_FLAGS = -m64
ARCH_NAME = X64

# library installation path
LIB_LOCATION = /usr/local/lib

# Platform Specific
CXX=g++
PORT    = linux4$(ARCH_NAME)
DEFS    =  -D__LINUX4 -D__X64

# import common make file
include Makefile.linux.common
