# 32-bit Architecture Dependent Config
ARCH_FLAGS = -m32
ARCH_NAME = X86

# library installation path
LIB_LOCATION = /usr/lib32

# Platform Specific
CXX=g++
PORT    = linux4$(ARCH_NAME)
DEFS    =  -D__LINUX4

# import common make file
include Makefile.linux.common
