spring.datasource.url=jdbc:postgresql://localhost:5432/votechain_db
spring.datasource.username=postgres
spring.datasource.password=aryan29jun
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
jwt.secret=votechain-super-secret-key-2025-blockchain-secure
jwt.expiration=86400000
spring.web.cors.allowed-origins=https://aryandeshpande11.github.io